# Generated by Django 5.2.8 on 2025-11-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='full_description',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Temp description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='focus',
            field=models.CharField(blank=True, choices=[('backend', 'Back-End Heavy'), ('fullstack', 'Full Stack'), ('cloud', 'Cloud-Ready')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
